### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by snitchjinx** [fredboudon/PyQGLViewer#4]
Hello! Thanks for sharing this nice tool.
I was trying to install PYQGLViewer, but got a bit confused about the dependencies, e.g. is it compatible with Python3 and PyQt5? It seems the configure.py is developed Python2. Would you elaborate the versions of dependencies more in the project description?
Thank you for your consideration!

**Comment by fredboudon** [comment]
Hi snitchjinx ,

Indeed, PyQGLViewer is compatible and actually distributed for  Python 3 and PyQt5.
I have updated the README.
Thanks for your comment.
